export { IndexPage } from './Index/IndexPage'
export { QuizItemPage } from './QuizItem/QuizItemPage'
export { QuizListPage } from './QuizList/QuizListPage'
export { QuizPlayPage } from './QuizPlay/QuizPlayPage'
export { ResultsItemPage } from './ResultsItem/ResultsItemPage'
export { ResultsListPage } from './ResultsList/ResultsListPage'