export { IndexPage } from './Index/IndexPage'
export { QuizItemPage } from './QuizItem/QuizItemPage'
export { QuizListPage } from './QuizList/QuizListPage'
export { QuizPlayPage } from './QuizPlay/QuizPlayPage'
export { AnswersItemPage } from './AnswersItem/AnswersItemPage'
export { AnswersListPage } from './AnswersList/AnswersListPage'